[package]
name = "prog-lang-dev1"
version = "0.1.0"
edition = "2021"

[features]
debug = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"

[dev-dependencies]
serial_test = "0.5.1"
